### ISSUE TITLE
Wrong Information

### ISSUE THREAD

**Issue by AbbasGoudarzi** [alisalehi1380/good-projects-for-good-developers#6]
Dear Ali, thank you for your efforts
However, the first two projects (News, shopline) do not have tests

**Comment by alisalehi1380** [comment]
Hi Dear @AbbasGoudarzi

I enjoyed your attention! ✌️
yes, the `News` repo doesn't have a test but you can find the test of the `shopline` project in the link below.

https://github.com/milwad-dev/shopline/blob/0.x-dev/Modules/About/Tests/Feature/AboutTest.php


you can fix the `News` in the readme file by PR.
Thank you in advance. 🙌
